### PR TITLE
Sidekick app to set max_map_count

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
@adamgraves-choices Can you rebase against `master` please so I can test the deployed version? Thanks!

**Comment by st3v3nhunt** [comment]
Some weird syntax going on. The build has failed: https://travis-ci.org/nhsuk/profiles-db-elastic/builds/235120868#L603
I've entered the same line locally and there are differences, probably best to type it in by hand.

**Comment by st3v3nhunt** [comment]
@adamgraves-choices Just to remind you the deployment isn't working. See the error: https://travis-ci.org/nhsuk/profiles-db-elastic/builds/235127671#L537

**Comment by st3v3nhunt** [comment]
The branch needs updating now too please @adamgraves-choices

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-17.dev.beta.nhschoices.net)

**Comment by adamgraves-choices** [comment]
@st3v3nhunt Fixed. YAML issues.

**Review by st3v3nhunt — APPROVED** [review]
All sorted 👍

**Pull request merged**
