### PR TITLE
Use Vault in CI scripts

### PR DESCRIPTION
**Pull request by adamgraves-choices**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-33.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-33.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-33.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-33.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-33.dev.beta.nhschoices.net)

**Review by st3v3nhunt — APPROVED** [review]
👍

**Pull request merged**
