### PR TITLE
:cow: Configuration for single service stack rancher deploy

### PR DESCRIPTION
**Pull request by st3v3nhunt**
In order for this to work in the integration environment the following change needed to be made. Set `ES_HOST` to `<rancher_stack_name>.<rancher_stack_name>-pr<number>` e.g. `profiles-db-elastic.profiles-db-elastic-pr-15`

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-15.dev.beta.nhschoices.net)

**Comment by st3v3nhunt** [comment]
I've marked this as `WIP` as the comment in the description about setting `ES_HOST` will need to be done automatically

**Comment by adamgraves-choices** [comment]
@st3v3nhunt I think adding an ENV var for `docker-compose.yml` ES_HOST with a value of `profiles-db-elastic:profiles-db-elastic` will work, as we should have a stack called that on each environment.

**Comment by st3v3nhunt** [comment]
@adamgraves-choices thanks. Although thinking about the comment I made, it should have been on the `gp-finder` repo. I'll remove the WIP tag from this I reckon it is good to go.

**Review by neilbmclaughlin — APPROVED** [review]

**Pull request merged**
