### PR TITLE
Add mappings for location search

### PR DESCRIPTION
**Pull request by neilbmclaughlin**

### CODE REVIEW

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-23.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-23.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-23.dev.beta.nhschoices.net)

**Comment by c2s-dev** [comment]
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-23.dev.beta.nhschoices.net)

**Comment by neilbmclaughlin** [comment]
Redundant and replaced by #24

**Pull request closed without merging**
